### ISSUE TITLE
Error in using the latest library version

### ISSUE THREAD

**Issue by zhubinsheng** [CuriousNikhil/neumorphic-compose#6]
/home/zbs/.gradle/caches/transforms-2/files-2.1/543eaf0df6ddea7b3bbea1e33f72e020/jetified-kotlin-stdlib-1.5.21.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
how can i do thx

**Comment by CuriousNikhil** [comment]
Which Kotlin version are you using? 
This library runs on Kotlin version 1.5.21. Could you please check tweaking your Kotlin version?
I'm yet to update this library to the latest version.
